### ISSUE TITLE
如何将这个东西引入到自己的项目并开始使用呢？　

### ISSUE THREAD

**Issue by qq752381473** [RingoStudio/ComWechatRobotCsharp#1]
@RingoStudio 如何将这个东西引入到自己的项目并开始使用呢？

**Comment by RingoStudio** [comment]
你好，在项目主页点击 Code - > Download Zip，或者打开git命令窗口，输入命令 git clone https://github.com/RingoStudio/ComWechatRobotCsharp，打开下载后的项目文件即可。
或者在你现有的项目中添加此项目。
